#include <stdio.h>

int main()
{
   int i,j[5],sum=0;
   for(i=0;i<5;i++)
   {
       scanf("%d%d%d%d%d", &j[0],&j[1],&j[2],&j[3],&j[4]);
       if(i==0)
       {
           if(j[0]==1)
           {
               sum+=4;
           }
           else
           if(j[1]==1)
           {
               sum+=3;
           }
           else
           if(j[2]==1)
           {
               sum+=2;
           }
           else
           if(j[3]==1)
           {
              sum+=3;
           }
           else
           if(j[4]==1)
           {
               sum+=4;
           }
       }
       else
       if(i==1)
       {
            if(j[0]==1)
           {
               sum+=3;
           }
           else
           if(j[1]==1)
           {
              sum+=2;
           }
           else
           if(j[2]==1)
           {
              sum+=1;
           }
           else
           if(j[3]==1)
           {
              sum+=2;
           }
           else
           if(j[4]==1)
           {
               sum+=3;
           }
       }
       else
       if(i==2)
       {
            if(j[0]==1)
           {
               sum+=2;
           }
           else
           if(j[1]==1)
           {
               sum+=1;
           }
           else
           if(j[2]==1)
           {
               sum+=0;
           }
           else
           if(j[3]==1)
           {
               sum+=1;
           }
           else
           if(j[4]==1)
           {
              sum+=2;
           }
       }
       else
       if(i==3)
       {
          if(j[0]==1)
           {
               sum+=3;
           }
           else
           if(j[1]==1)
           {
               sum+=2;
           }
           else
           if(j[2]==1)
           {
               sum+=1;
           }
           else
           if(j[3]==1)
           {
              sum+=2;
           }
           else
           if(j[4]==1)
           {
               sum+=3;
           }  
       }
       else
       if(i==4)
       {
            if(j[0]==1)
           {
               sum+=4;
           }
           else
           if(j[1]==1)
           {
               sum+=3;
           }
           else
           if(j[2]==1)
           {
               sum+=2;
           }
           else
           if(j[3]==1)
           {
               sum+=3;
           }
           else
           if(j[4]==1)
           {
               sum+=4;
           }
       }
   
       
   }
   printf("%d",sum);

    return 0;
}